### ISSUE TITLE
No invite link or self hosting instructions

### ISSUE THREAD

**Issue by allipsee** [FrostByte266/hackweek_bot#1]
Hello, I was looking forward to using your bot in my server, but as I see there is no link for an invite neither for self-hosting. Why??? @FrostByte266

**Comment by FrostByte266** [comment]
There is no hosted bot user for this, however to host one yourself you can follow these steps: 
* Install python and all dependencies listed in the readme
* Clone this repository
* Run main.py and enter your bot user token when prompted (if you are confused what a bot token is, or you don't know how to get one, you can find documentation [here](https://discordpy.readthedocs.io/en/latest/discord.html))
