### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MonarchActual** [FrostByte266/hackweek_bot#2]
Hey,
I would really like to use some parts of your amazing bot for my own (just personal use).
Right now your bot has no license, which prevents me from modifying or using parts of your bot.

I would really appreciate it if you would add a license like [MIT](https://choosealicense.com/licenses/mit/) for example. It requires others like me to give credit but freely use your code.

The Website https://choosealicense.com/ helps you decide which license to use if you don't want to give anyone permission to do anything.

Thanks in advance for thinking about it.

**Comment by FrostByte266** [comment]
I have gone ahead and attached an MIT license to the repository (commit: 8b56fce5e772191c510dfdcd9212b5699e69e292). Thank you for your interest in our bot and I hope your project turns out well! ``
