### ISSUE TITLE
Bot Wont Respond | Config Loop

### ISSUE THREAD

**Issue by ClearlyElevated** [FrostByte266/hackweek_bot#3]
Cannot get the bot to respond. do you guys have a support server? I have it installed correctly. im trying to make a video review of all of the winning bots from the contest. and yours is the one i am using for the most realistic/useable application

**Comment by ephreal** [comment]
Could you provide some more details? It'd help with pinpointing the issue for you. Some questions I'd ask are

Does the bot connect to the server when you run the bot?
Are you running the docker version of the bot?
What python version are you using?
Are you running the bot on Linux, Mac, or Windows?
Have you changed the bot command prefix (b! by default)?

I'll do a clean clone and setup of the bot myself in a few hours when I get the chance just to make sure there's not something causing issues there.

**Comment by ClearlyElevated** [comment]
I tried the Mac version at first but I couldn't figure it out for the life of me. Just got a new computer lastnight but I couldn't figure out how to delete the old version of python I downloaded. So I moved to my windows pc. Tried docker version but my version of Windows 10 isn't supported. So I tried the non docked version. I input my bot token. And the bot came online. And then it kept throwing a error that said something about config. So I assume it couldn't find the token. The bot came online. But everytime I tried a command that's when the error would come up. I'm on the latest version of python as I run the ModMail bot.i run my existing python bot in a venv so that wouldn't be the issue would it? 

`EDIT: I ALSO DIDNT CHANGE THS BOT PREFIX. IT STILL IS b!`

**Comment by ClearlyElevated** [comment]
I am just trying to do a review of the hackweek bots I PERSONALLY liked and this one offers the most useful features for the application I would be using/testing the bots on. And at the end of the video. I am gonna show this one if I can figure it out. And one other bot for the best selfhosted bots for s video for my server users since I seem to get that question a lot

**Comment by ephreal** [comment]
I'm not sure how it happened, but it appears that the bot was looking for the config in the wrong location. I have since fixed that. Please either redownload main.py and overwrite the main.py in the bot folder, or redownload the project and try running the bot fresh. Either will do.

Let me know if you still have any issues!

**Comment by ephreal** [comment]
I've been asked to let you know that we are also working on an updated version of the bot for the coding community discord server. If you'd like to check it out, it's repository is hosted by the same person at https://github.com/FrostByte266/coding_community_bot . Some of our changes are put into the master branch, and the dev branch is currently very stable and has some new features added in for bot management, additional user verification, and more. Check it out if you get the chance :)

**Comment by ephreal** [comment]
It's been a few days since I last heard from you, I'm assuming my fix has worked. If you have any other issues, please let us know and we'll help you get setup.

**Comment by ClearlyElevated** [comment]
Sorry about that

**Comment by ClearlyElevated** [comment]
I haven't fixed the issue. Well I kinda did. I was able to get it to respond but the only thing that really worked was the plot commands. Everything else kept looping

**Comment by ClearlyElevated** [comment]
So I can just replace the main.py from the dev branch also right? Or should I just clone a fresh copy

**Comment by ClearlyElevated** [comment]
I know you guys don't actually offer Support. But I was wondering if you had a discord server where you release the change logs and keep people updated and what not. I don't really get on here much at all only really if I am updating one of my projects. Would be easier for me to follow the bot updates via disco

**Comment by ephreal** [comment]
Yes, replacing the main.py should do the trick, that was all I had to change.

Unfortunately, as far as I know, we don't have a dedicated discord for the bot. I'll raise the question with the maintainer of the bot though.

**Comment by ephreal** [comment]
I don't believe there is any plans for a update release cycle for the bot on discord. I asked real quick and received back this answer.

"There are no planned updates, upgrades, new features, or known maintenance planned for the hack week bot. The intent for the hackweek bot is to keep it in stasis for people who wanted to use the hackbot in the condition it was in when it won. All known future development efforts are being placed on the coding community bot repo ( https://github.com/FrostByte266/coding_community_bot  ). The only possible reason we would do any additional push to the hack week bot is if another bug issue was opened.
Desired features are not bugs"

I just wish to note that desired features will be added to the coding community bot, which will continue to improve with time.

**Comment by ClearlyElevated** [comment]
Okay thank you. Im gonna give it a go and let you know whats up. thanks for the quick response.

**Comment by ClearlyElevated** [comment]
After trying to install dev branch https://hatstebin-plus.herokuapp.com/J2hWq4tWlt

**Comment by ephreal** [comment]
I'm not sure what the hastebin is supposed to show.... it's just a blinking cursor. Just to verify, you downloaded from here?
https://github.com/FrostByte266/coding_community_bot/tree/dev

**Comment by ephreal** [comment]
I just gave the dev branch a clean clone and run, it started just fine. Is it possible that you don't have the dependencies installed?
`
pip install discord matplotlib networkx pandas prawn
`

**Comment by ClearlyElevated** [comment]
I will do a clean install instead of just replacing main.py
